name: Build and Release

on:
  release:
    types: [published]
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build
        run: mvn -B -ntp -DskipTests package
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.xar
          tag_name: ${{ github.event.release.tag_name || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
