name: Build and Release XAR

on:
  release:
    types: [published]
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Determine draw.io version
        id: vars
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=drawio.version -q -DforceStdout)
          echo "drawio_version=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Clone draw.io packaging project
        run: git clone https://github.com/seclution/draw.io.git /tmp/drawio
      - name: Build draw.io WebJar
        run: mvn -pl draw.io-webjar -am clean package -Ddraw.io.version=${{ steps.vars.outputs.drawio_version }} --settings ${{ github.workspace }}/.github/maven-settings.xml
        working-directory: /tmp/drawio
      - name: Install draw.io parent POM
        run: |
          mvn install:install-file -Dfile=/tmp/drawio/pom.xml \
            -DgroupId=org.xwiki.contrib -DartifactId=draw.io-parent \
            -Dversion=${{ steps.vars.outputs.drawio_version }}-1-SNAPSHOT -Dpackaging=pom
      - name: Install WebJar to local Maven repo
        run: |
          JAR_PATH=$(ls /tmp/drawio/draw.io-webjar/target/*.jar | head -n1)
          mvn install:install-file -Dfile=$JAR_PATH -DgroupId=org.xwiki.contrib -DartifactId=draw.io \
            -Dversion=${{ steps.vars.outputs.drawio_version }} -Dpackaging=jar
      - name: Build with Maven
        run: mvn -B package --settings .github/maven-settings.xml
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: target/*.xar
          tag: ${{ github.event.release.tag_name || github.ref_name }}
          allowUpdates: true
